name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: i18n-sweep
          bump-minor-pre-major: true
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"refactor","section":"Refactors","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"build","section":"Build System","hidden":true},
              {"type":"chore","section":"Chores","hidden":true},
              {"type":"test","section":"Tests","hidden":true}
            ]


